### ISSUE TITLE
All download links on http://praisenter.org/download/ 404

### ISSUE THREAD

**Issue by NucleaPeon** [praisenter/praisenter#34]
I am unable to download releases from the webpage http://praisenter.org/download/ because I receive 404 errors.

![Screenshot_20230927_155858](https://github.com/wnbittle/praisenter/assets/1475151/613618db-bfdd-4b72-a058-a62fdc87f614)

Tried both OS X and Windows. Linux webstart and archive links also 404.

**Comment by wnbittle** [comment]
I really need to just take that site down or replace it with a github site.  Those are really old builds and shouldn't be used anymore.  The site needs an overhaul too.

**Comment by wnbittle** [comment]
They Windows and Linux builds can be found here: https://github.com/wnbittle/praisenter/tags.  I don't have a MacOS build unfortunately.

**Comment by wnbittle** [comment]
I've created a github pages site to replace the old praisenter.org and updated the download links
