### ISSUE TITLE
Resolution doesnt show up correctly on screen

### ISSUE THREAD

**Issue by CentroDeFeMinistry** [praisenter/praisenter#41]
The presentation shows up as a small box in the corner instead of on the entire screen
![image](https://github.com/user-attachments/assets/7730b9d4-77eb-4bac-8d88-c1282d6c18da)

**Comment by wnbittle** [comment]
What version of Praisenter are you running?  The latest version should have that fixed

**Comment by wnbittle** [comment]
Closing, haven't heard any feedback in a week.
